{% set name = "fastprogress" %}
{% set version = "1.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 852db534ce4dab1fb6ac5c5c57215a5f76de47e07175fedcbaa8c2cfedc59926

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - fastprogress

about:
  home: https://github.com/fastai/fastprogress
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A fast and simple progress bar for Jupyter Notebook and console.
  dev_url: https://github.com/fastai/fastprogress
  doc_url: https://github.com/fastai/fastprogress

extra:
  recipe-maintainers:
    - andersy005
